In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv')

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [8]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [17]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [18]:
y_pred = clf1.predict(X_test)
y_pred1 = clf2.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [20]:
print('Acc_LR',accuracy_score(y_test,y_pred))
print('Acc_DT',accuracy_score(y_test,y_pred1))

Acc_LR 0.8536585365853658
Acc_DT 0.9804878048780488

In [13]:
confusion_matrix(y_test,y_pred)

array([[82, 23],
       [ 7, 93]])

In [15]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  82  23
1   7  93

In [21]:
print("DT Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

DT Confusion Matrix

     0    1
0  101    4
1    0  100

In [29]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred
result['Decision Tree Prediction'] = y_pred1

In [33]:
result.sample(10)

      Actual Label  Logistic Regression Prediction  Decision Tree Prediction
869              1                               1                         1
1000             0                               0                         0
818              1                               1                         1
338              0                               1                         0
643              1                               0                         1
239              0                               1                         0
687              0                               0                         0
322              0                               0                         0
451              1                               1                         1
530              0                               0                         0

In [30]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [34]:
print('Logistic Reg')
print('-'*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred),columns=list(range(0,2)))
print(cdf)
print('-'*50)
print('Precision',precision_score(y_test,y_pred))
print('recall_score',recall_score(y_test,y_pred))
print('f1_score',f1_score(y_test,y_pred))

Logistic Reg
--------------------------------------------------
    0   1
0  82  23
1   7  93
--------------------------------------------------
Precision 0.8017241379310345
recall_score 0.93
f1_score 0.8611111111111112

In [35]:
print('DT')
print('-'*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print('-'*50)
print('Precision',precision_score(y_test,y_pred1))
print('recall_score',recall_score(y_test,y_pred1))
print('f1_score',f1_score(y_test,y_pred1))

DT
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision 0.9615384615384616
recall_score 1.0
f1_score 0.9803921568627451